from enum import StrEnum


class Provenance(StrEnum):
    OFFICIAL = "OFFICIAL"
    USER = "USER"
    CALCULATED = "CALCULATED"
    AI_INFERENCE = "AI_INFERENCE"
    SYNTHETIC = "SYNTHETIC"


class IssueState(StrEnum):
    DETECTED = "DETECTED"
    NEEDS_CONFIRMATION = "NEEDS_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    ACTION_READY = "ACTION_READY"
    SUBMITTED = "SUBMITTED"
    ACCEPTED = "ACCEPTED"
    WORK_IN_PROGRESS = "WORK_IN_PROGRESS"
    DONE_PENDING_VERIFICATION = "DONE_PENDING_VERIFICATION"
    VERIFIED = "VERIFIED"
    CLOSED = "CLOSED"
    REOPENED = "REOPENED"
    DUPLICATE = "DUPLICATE"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


class WorkOrderState(StrEnum):
    NEW = "NEW"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"
    ACCEPTED = "ACCEPTED"
    REWORK_REQUIRED = "REWORK_REQUIRED"


class InitiativeState(StrEnum):
    DETECTED = "DETECTED"
    DRAFT = "DRAFT"
    DISCUSSION = "DISCUSSION"
    INFORMAL_POLL = "INFORMAL_POLL"
    RESULT = "RESULT"
    CLOSED = "CLOSED"
    FORMAL_HANDOFF_REQUIRED = "FORMAL_HANDOFF_REQUIRED"

